apiVersion: apps/v1
kind: Deployment
metadata:
  name: draw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: draw
  template:
    metadata:
      labels:
        app: draw
    spec:
      containers:
        - image: pbsem2/drawer_image:latest
          name: draw
          imagePullPolicy: Always
          env:
            - name: DBURI
              value: jdbc:postgresql://batyr.db.elephantsql.com:5432/obauputb
            - name: DBUSERNAME
              value: obauputb
            - name: PASSWORD
              #value: IyELRXpf5tGzTJhhojCSjUYFzXWOETNN
              valueFrom:
                secretKeyRef:
                    name: pg-pass
                    key: password
            - name: CONFIGIP
              value: optional:configserver:http://52.226.106.6:8888/
          ports:
            - containerPort: 8081
              name: server
          livenessProbe:
            httpGet:
              path: api/draw/health/liveness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: api/draw/health/readiness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: draw
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: server
  selector:
    app: draw



