apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-editor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-editor
  template:
    metadata:
      labels:
        app: user-editor
    spec:
      containers:
        - image: pbsem2/new_image:latest
          name: user-editor
          imagePullPolicy: "Always"
          env:
            - name: DBURI
              value: jdbc:postgresql://batyr.db.elephantsql.com:5432/obauputb
            - name: DBUSERNAME
              value: obauputb
            - name: PASSWORD
              #value: IyELRXpf5tGzTJhhojCSjUYFzXWOETNN
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: password
            - name: CONFIGIP
              value: optional:configserver:http://52.226.106.6:8888/
          ports:
            - containerPort: 8082
              name: server
          livenessProbe:
            httpGet:
              path: api/users/health/liveness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: api/users/health/readiness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: user-editor
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: user-editor



